<a href="https://colab.research.google.com/github/mumng/Python-note/blob/master/240429_Numpy_%EA%B8%B0%EC%B4%88(%EC%8B%A4%EC%8A%B5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

numpy, pandas, scikit -> CPU에 최적화된 라이브러리, but GPU는 전혀 지원하지 않는다.

h2o.ai, cudf, cuml, RAPIDS(GPU acceleration for data science) -> GPU 연산시 사용


### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

### 1.1. Numpy Array creation

In [9]:
# numpy 라이브러리를 불러옵니다.

import numpy as np

In [10]:
# 파이썬 리스트 선언
data = [1,2,3,4]

In [11]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1,2],[3,4]]

In [12]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.

np.array(data)

array([1, 2, 3, 4])

In [20]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2.shape

(2, 2)

In [34]:
# 0부터 9까지 숫자를 자동으로 생성한 array
print(np.arange(0,10)) # (10,) -> 원소 10개짜리 1차원 array
np.zeros(shape=(5,3)) # 5 x 3 2차원 array를 생성하고 값을 모두 0으로
np.linspace(0, 1, 10)  # [start, stop]의 구간을 10개의 균등한 구간으로 잘라서 각 원소로 이뤄진 1차원 numpy array 생성
np.random.randn(5,3) # 5 x 3 numpy array를 만들고, 각 원소는 표준정규분포에서 sampling

[0 1 2 3 4 5 6 7 8 9]


array([[-0.92014444,  0.57888877, -0.91194579],
       [ 0.46901213,  0.08235037, -1.76026521],
       [ 0.07231647,  0.63325178,  0.21193416],
       [ 1.13169395,  0.28927482, -1.02641971],
       [-0.94652721,  0.32962378,  0.20056021]])

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array


### 1.2. Reshaping array

In [ ]:
# 3 x 3 행렬을 만들어봅시다.
# 1차원 : vector
# 2차원 : matrix
# 3차원이상 : tensor
# shape()은 가장 바깥 괄호부터 원소의 개수를 순차적으로 지정함
x = np.zeros(shape=(5,))
x = np.zeros(shape=(5,3))
x = np.zeros(shape=(5,3,4))  # 5개의 3x4 matrix
x = np.zeros(shape=(32,3,224,224)) # 사용예: 224 x 224크기의 3개(RGB)의 channel을 가지고 있는 이미지가 32개
x

In [ ]:
# reshape을 이용하여 만들어봅시다.
x = np.arange(1, 10).reshape(9, 1) # 1~10으로 이루어진 9개 원소의 numpy array를 reshape()을 이용하여 9x1 matrix(column형태)로 변형
y = np.arange(1, 10).reshape(9,) # 1차원 vector
z = np.arange(1,121).reshape(8,-1)  # 첫 번째 인수인 8은 새로운 배열이 8개의 행을 가져야 함을 의미, 두 번째 인수인 -1은 NumPy에게 나머지 차원(열의 수)을 자동으로 계산하게 함
print(x)
print(y)
print(z)

In [ ]:
# row vector를 column vector로


In [ ]:
# 펼치기


### 1.3. Concatenation of arrays

In [40]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?

# arr1와 arr2를 합칩니다
arr1 + arr2

array([5, 7, 9])

In [41]:
# stacking vertically
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# stacking horizontally
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [45]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array((1,2,3))
v2 = np.array((4,5,6))

In [46]:
# 리스트로 더하기 연산해보기
v1 + v2

array([5, 7, 9])

In [ ]:
#  vector addition


In [ ]:
#  vector subtraction


In [47]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [48]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [49]:
# dot product
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [50]:
arr1 = np.array([1,2,3])

In [59]:
arr2 = np.array([[-1,-1,-1],
                 [1, 1, 1]])
arr3 = arr2.reshape(3,2)
arr3

array([[-1, -1],
       [-1,  1],
       [ 1,  1]])

In [ ]:
# 2개의 array를 더해보면?
arr1 + arr2 # (3,) + (2,3)은 shape이 맞아서 broadcasting되어 계산됨
arr1 + arr3 # (3,) + (3,2)는 shape이 안맞아서 error
# (5,) + (3,4,5) -> 계산 됨
# (3,4) + (5,3,4) -> 계산 됨
# (3,4) + (3,4,5) -> 계산 X
# => 두 개중 작은 차원을 가진 ndarray가 큰차원을 가진 ndarray의 작은부분과 일치하면 bloadcasting 연산 가능

In [58]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [62]:
# f = lambda x : 1/x
arr1 / 1

## Universal Function
1/ arr1 ## 각원소를 reverse 연산 -> 이 연산의 결과는 아래와 같은 함수를 사용한 것과 동일한 결과를 준다.

def reverse_num(x):
    return 1/x
for i in range(len(arr1)):
    arr1[i] = reverse_num(arr1[i])

array([1.        , 0.5       , 0.33333333])

In [ ]:
# f = lambda x : x + 2


### 1.6. Indexing


In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

In [ ]:
# arr2의 2row, 3column 원소 = 7


In [ ]:
# arr2의 세번째 column [3, 7, 11]


In [ ]:
# arr2의 두번째 row


## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions

In [66]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
# pseudo-random : 현재 시각(ns)
np.random.seed(42) # set seed number -> seed() 인자 숫자를 동일하게 하면 random으로 나온 숫자가 항상 일정하다. random 값을 사용하되, 그 값을 일정하게 하고 싶을때 seed()에 특정 인자로 고정함.
mat1 = np.random.randn(5,3) # 위에 seed()의 인자 42를 바꾸지 않는 한 일정한 무작위수 값이 나옴
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [69]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [70]:
# mat1 제곱하기


<ipython-input-70-8386b2ce52e8>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(mat1)


array([[0.70477951,        nan, 0.80479099],
       [1.23411096,        nan,        nan],
       [1.25666734, 0.87603352,        nan],
       [0.73658675,        nan,        nan],
       [0.49189661,        nan,        nan]])

In [72]:
# mat1의 제곱근 구하기
np.sqrt(mat1.astype('complex'))

array([[0.70477951+0.j        , 0.        +0.37183908j,
        0.80479099+0.j        ],
       [1.23411096+0.j        , 0.        +0.48389397j,
        0.        +0.48387701j],
       [1.25666734+0.j        , 0.87603352+0.j        ,
        0.        +0.68518201j],
       [0.73658675+0.j        , 0.        +0.68074789j,
        0.        +0.68244396j],
       [0.49189661+0.j        , 0.        +1.38321374j,
        0.        +1.31336127j]])

In [73]:
# linear algebra functions
vec = np.array([1, 2, 3])

# 1. norm
np.linalg.norm(vec)


# 2. eigenvalue
mat = np.array([[1, 0],
                [0, 1]])
np.linalg.eig(mat)

EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))

### 2.2. Aggregation functions

In [77]:
np.random.seed(0xC0FFEE) ## seed()에 인자가 바뀌지 않는한 아래 random 값은 항상 유지됨
mat2 = np.random.rand(3, 2)
mat2

array([[0.57290783, 0.81519505],
       [0.92585076, 0.09358959],
       [0.26716135, 0.96059676]])

In [84]:
# Summation
print(np.sum(mat2, axis=0)) ## axis=0 : column방향으로
print(np.sum(mat2, axis=1)) ## axis=1 : row 방향

[1.76591995 1.86938141]
[1.38810288 1.01944035 1.22775812]


In [86]:
# mean
np.mean(mat2, axis=1)

array([0.69405144, 0.50972018, 0.61387906])

In [ ]:
# std


In [89]:
# min, max
print(np.min(mat2))
print(np.min(mat2, axis=0))

0.09358959363758512
[0.26716135 0.09358959]


In [90]:
# 최소값이 있는 Index
np.argmin(mat2, axis=0) # 각 column에서 min의 index

array([2, 1])

In [91]:
# 최대값이 있는 Index
np.argmax(mat2, axis=0)

array([1, 2])

### <numpy dtype>
####1. int8, int16, int32, int64
* 정수 1개를 표현하는데 사용하는 bit의 수 00000000 ~ 11111111

####2. float32, float64 : 실수 1개를 표현하는데 사용하는 bit의 수
####3. uint8, uint16

In [93]:
#numpy datatype별 정수 범위
print(f"int8 : -{2**7} ~ {2**7 - 1}")
print(f"int16 : -{2**15} ~ {2**15 - 1}")
print(f"int32 : -{2**31} ~ {2**31 - 1}")
print(f"int64 : -{2**63} ~ {2**63 - 1}")

int8 : -128 ~ 127
int16 : -32768 ~ 32767
int32 : -2147483648 ~ 2147483647
int64 : -9223372036854775808 ~ 9223372036854775807


In [ ]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)


In [ ]:
# index를 정렬


## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [97]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))

    for i in range(len(values)):
        output[i] = 1.0 / values[i]

    return output

In [100]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1,100,100)

In [101]:
%timeit reverse_num(big_array)

200 µs ± 37.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [102]:
%timeit 1.0 / big_array

1.65 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# python for문을 이용하는 것 보다 numpy universal function을 이용하는 것이 대용량 데이터 연산할수록 속도차이가 커진다.